### PR TITLE
fix: use OF tooltip instead of title attribute

### PR DESCRIPTION
**Pull request by pownkel**
#### Description of changes

(Fix for trusted tester bug)

Some of our links use the `title` attribute for tooltips, which is not recommended, because it is not well supported and Chrome does not make the tooltip visible on focus. This PR replaces several instances of `title` tooltips with the office fabric tooltip, which we use for the target page link in details view, and which does become visible on focus.

This PR affects:
- Guidance links in "Getting started" assessment pages
- Guidance link in tab stops page
- Guidance links in ad hoc tools popup
- "axe-core" link in footer of extension popup

Minor effects to accessible names read by NVDA:
- axe-core link: previously "axe-core  link  Navigate to axe-core npm page", now "Navigate to axe-core npm page  link"
- ad hoc tools guidance links: previously "How to test X  link  Guidance", now "How to text X guidance  link"

Before:
guidance tooltip with title attribute
axe-core tooltip with title attribute

After:
guidance tooptip with office fabric
axe-core tooltip with office fabric

#### Pull request checklist

- [x] Addresses an existing issue: #1785883
- [x] Ran `yarn fastpass`
- [x] Added/updated relevant unit test(s) (and ran `yarn test`)
- [x] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x] PR title *AND* final merge commit title both start with a semantic tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). See `CONTRIBUTING.md`.
- [x] (UI changes only) Added screenshots/GIFs to description above
- [x] (UI changes only) Verified usability with NVDA/JAWS

### CODE REVIEW

**Comment by lisli1** [comment]
Is there a difference in how the guidance links look in high contrast mode?

**Comment by pownkel** [comment]
> Is there a difference in how the guidance links look in high contrast mode?

The link looks the same, but the tooltip has a black background:

high contrast

@ferBonnin is the lack of contrast an issue?

**Comment by ferBonnin** [comment]
> @ferBonnin is the lack of contrast an issue?
for usability, it would be good to have a border (white), but not required. we have this same behaviour in the other tooltip in prod and also, the contrast in the text is good.

**Comment by pownkel** [comment]
> for usability, it would be good to have a border (white), but not required. we have this same behaviour in the other tooltip in prod and also, the contrast in the text is good.

Ok, added a white outline in high contrast mode (which also affects the switch to target page tooltip):
high contrast outline

**Review by lisli1 — APPROVED** [review]
LGTM

**Pull request merged**
