### PR TITLE
[Issue Filing] remove feature flag and unused code

### PR DESCRIPTION
**Pull request by haonliu**
#### Description of changes

remove feature flag and unused code
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Added relevant unit test for your changes. (`npm run test`)
- [x] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x] Ran precheckin (`npm run precheckin`)
- [ ] Added screenshots/GIFs for UI changes.

### CODE REVIEW

**Comment by peterdur** [comment]
Can bug-button.tsx (and test, snapshot) also be removed?

**Comment by haonliu** [comment]
> Can bug-button.tsx (and test, snapshot) also be removed?

Removed!

**Comment by peterdur** [comment]
There is also obsolete code in issue-tracker.tsx and plumbing the `issueTrackerPath` through the extension... removing that code probably makes sense to do in a separate PR as about 29 files would be affected.

**Comment by lisli1** [comment]
Are there any UI changes?

**Comment by haonliu** [comment]
> Are there any UI changes?

No UI changes, only removing unused code.

**Pull request merged**
