### PR TITLE
fix: update subtitle text

### PR DESCRIPTION
**Pull request by smoralesd**
#### Description of changes

Update subtitle for automated checks (on FastPass) to match new requirement. Update container size to control text wrapping

**text content**
01 - updated subtitle

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #0000
   - does not apply
- [x] Added relevant unit test for your changes. (`npm run test`)
   - does not apply
- [x] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
   - does not apply
- [x] Ran precheckin (`npm run precheckin`)
- [x] (UI changes only) Added screenshots/GIFs to description above
- [x] (UI changes only) Verified usability with NVDA/JAWS
   - does not apply

### CODE REVIEW

**Comment by smoralesd** [comment]
make sure @ferBonnin has a chance to review before you merge

**Comment by smoralesd** [comment]
@msft-github-bot make sure @ferBonnin has a chance to review before you merge

**Comment by smoralesd** [comment]
@msft-github-bot do not merge unless @ferBonnin approves.

**Comment by ferBonnin** [comment]
is the line break set always? would be better to have assessment in the same line

**Comment by smoralesd** [comment]
> is the line break set always? would be better to have assessment in the same line

@ferBonnin There is no line break. The text is wrapping because we have set the max width of the text container (it's like this from master, not sure that was intended or not). I updated the max width so the text itself will use the available space and wrap accordingly (please see the animated gif)

**Pull request merged**
