### PR TITLE
Fix typo for #672 and fix typo in git-branch-setup.md

### LINKED ISSUE #672: Incorrect string "model" instead of "modal"
## Describe the bug
I hope this image will explain the bug:
image

Just a typo, where the word model is used when modal should be used. Highlighted with a red circle.

### PR DESCRIPTION
**Pull request by mdecorte**
#### Description of changes

Fixes typo as requested by #672 plus one extra typo spotted in `./docs/git-branch-setup.md`

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #672
- [ ] Added relevant unit test for your changes. (`npm run test`)
- [ ] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [ ] Ran precheckin (`npm run precheckin`)
- [ ] (UI changes only) Added screenshots/GIFs to description above
- [ ] (UI changes only) Verified usability with NVDA/JAWS

### CODE REVIEW

**Comment by smoralesd** [comment]
Mention of #677 on the description seems incorrect

**Comment by ferBonnin** [comment]
hey @mdecorte thanks for the PR! would you be interested in us sending you a Sticker of our mascot, Ada?

**Comment by mdecorte** [comment]
No problem! Sticker would be nice, I live in the Netherlands though :)

Address is [Claes de Vrieselaan 20d, 3021JP Rotterdam, the Netherlands] if
that's no issue.

Good work on the tool, keep it up!

Kind regards,
Marius de Corte

**Comment by ferBonnin** [comment]
awesome! sticker is on its way :)

**Pull request merged**
