### PR TITLE
feat(duplicate-id): exclude duplicate-id rule from automated checks

### PR DESCRIPTION
**Pull request by tohmjudson-ms**
#### Details

Adds a custom rule to tag 'duplicate-id' errors as best practice

##### Motivation

Addresses issue #4102

##### Context

This PR only addresses `duplicate-id`, which is marked as **Impact**: Minor by axe-core. It does not change and not `duplicate-id-active` (**Impact**: Serious) or `duplicate-id-aria` (**Impact**: Critical).

#### Pull request checklist

- [x] Addresses an existing issue: #4102 
- [x] Ran `yarn fastpass`
- [x] Added/updated relevant unit test(s) (and ran `yarn test`)
- [ ] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x] PR title *AND* final merge commit title both start with a semantic tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). See `CONTRIBUTING.md`.
- [ ] (UI changes only) Added screenshots/GIFs to description above
- [ ] (UI changes only) Verified usability with NVDA/JAWS

### CODE REVIEW

**Comment by tohmjudson-ms** [comment]
Note: this most likely needs a test as well. I could definitely use some help on that to meet standards

**Comment by dbjorge** [comment]
Thanks for the contribution, @tohmjudson-ms! Our usual mechanism for suppressing rules that axe-core includes by default is the `explicitRuleOverrides` variable in `/src/scanner/get-rule-inclusions.ts`; I think that would probably be the preferred place to update, rather than using a custom rule config. You can use the description from #4102 in the `reason` field, something like this:

```ts
    'duplicate-id': {
        status: 'excluded',
        reason: `
            Based on feedback from users we tested to check the user impact of duplicate ID failures
            on static elements. We found no user impact on the experience with any of the ATs
            including Narrator, JAWS, NVDA, Dragon, Windows Speech Recognition. After further
            discussions with the Tooling Advisory Board, we decided to make this a best practice
            rule. See #4102.`,
    },
```

To update the corresponding unit test, you'd need to update a jest snapshot (`yarn test -- -- -u -- get-rule-inclusions.test`)

It looks like there are also a few end to end tests that involve pinning scan results which are impacted by this change; the PR build results should point you at which test cases need updates. It looks like there will be one case from the web e2es you'll need to change a number for and that you'll need to regenerate snapshots for the report e2es (`yarn test:report:e2e -u`)

**Comment by tohmjudson-ms** [comment]
Awesome @dbjorge! That makes things so much more clear to me, thank you! I updated as you requested. I still need to update the test cases, which I hope to do very shortly

**Review by dbjorge — APPROVED** [review]
Thanks for the contribution, LGTM!

**Pull request merged**
