### PR TITLE
feat(office-fabric): update to office fabric 7

### LINKED ISSUE #777: WCAG 2.1: 1.4.13 tooltip in modal dialog is not dismissible
## Describe the bug
related to S.C. 1.4.13, tooltip in modal dialog is not dismissable using keyboard only.

**To Reproduce**
1. Go to any page and continue an assessment
2. Dialog to continue or start new assessment appear
3. using keyboard, navigate through the links
4. try to press esc to dismiss tooltip, you can't

## Expected behavior
tooltip should be dismissable using esc key

## Screenshots

Screenshot tooltip in the modal dialog

## Extension (please complete the following information)

- OS: [e.g. Windows/Mac] Windows 
- Version [e.g. 1.140.1] 2.4.1
- Browser Version [e.g Chrome 71.0] Version 74.0.3729.169
- Target Page [e.g www.bing.com] any

## Are you willing to submit a PR?

If asked, will you be willing to submit a PR to fix this bug? No

## Did you search for similar existing issues?

Yes

### LINKED ISSUE #1758: In details view, console exception is thrown for violating Content Security Policy directive
## Describe the bug

- Goto any web page & then Open Assessment in details view.
- Click on any test step.
- Open dev tools & goto console on the details view.

Exception thrown:
Refused to run the JavaScript URL because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://az416426.vo.msecnd.net". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

## Extension (please complete the following information)

- OS: [e.g. Windows/Mac] - Windows
- Version [e.g. 1.140.1] - This is happening in all our extensions. Not sure when this was introduced
- Browser Version [e.g Chrome 71.0] - 78.0.3904.108

### PR DESCRIPTION
**Pull request by smoralesd**
#### Description of changes

This PR is to update office fabric to version 7 and to fix any issues we may encounter after the update.

This PR also:
- fixes #777 
- fixes #1758

**NOTE** this PR is just a re-brand of an older PR (#1924). I had to create a new PR because the build on the old one got stock (never getting status back from ADO)

#### Pull request checklist
- [x] Addresses an existing issue: part of WI # 1560365
- [x] Ran `yarn fastpass`
- [x] Added/updated relevant unit test(s) (and ran `yarn test`)
- [x] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x] PR title *AND* final merge commit title both start with a semantic tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). Check workflow guide at: `<rootDir>/docs/workflow.md`
- [ ] (UI changes only) Added screenshots/GIFs to description above
- [x] (UI changes only) Verified usability with NVDA/JAWS

### CODE REVIEW

**Comment by smoralesd** [comment]
This can be tested on AI-Web Playground 2020.1.8.2334

**Comment by dbjorge** [comment]
The code looks good to me, but I'd like to walk through the changelog from office fabric to look for any specific changes we want to test before approving.

**Comment by dbjorge** [comment]
The shadows and icon sizes in some dropdown menus is different (ignore the difference in gear color here, that's also updated in canary):

Before/Production (small icons, thick border/shadow):

image

After/Playground (larger icons, more subtle border/shadow):

image

Is this expected/desired?

**Comment by dbjorge** [comment]
Weird issue with the "continue previous assessment" dialog involving tooltips on links.

Before/Canary (note that the question mark still looks weird, but stays put as tooltip flashes):
gif of canary build hovering links in continue assessment dialog


After/Playground (note the question mark moving around weirdly as tooltip shows/hides, also note button style changes):
gif of playground build hovering links in continue assessment dialog

**Comment by smoralesd** [comment]
> The shadows and icon sizes in some dropdown menus is different (ignore the difference in gear color here, that's also updated in canary):
> Before/Production (small icons, thick border/shadow):
> 
> After/Playground (larger icons, more subtle border/shadow):
> 
> Is this expected/desired?

@ferBonnin and myself saw this too and decided the icon size change on the contextual menus is fine. Sorry I forgot to mention this on the PR description.

**Comment by smoralesd** [comment]
> Weird issue with the "continue previous assessment" dialog involving tooltips on links.
> Before/Canary (note that the question mark still looks weird, but stays put as tooltip flashes):
> 
> After/Playground (note the question mark moving around weirdly as tooltip shows/hides, also note button style changes):

Good catch! I created a user story (1560365) to track this but I would like very much complete this PR as we have other small changes we want to make. Completing this PR will help unlock those user stories (and also parallelize them).

**Pull request merged**
