### PR TITLE
fix: update landmark visualizations

### LINKED ISSUE #694: color contrast issue with Landmarks over target page
## Describe the bug
Landmarks drawn over the target page from adhoc tools or Assessment, do not comply with color contrast.

**To Reproduce**

1. Go to https://www.washington.edu/accesscomputing/AU/after.html#
2. turn on Landmarks from adhoc tools or assessment
3. See color contrast issues:

- purple: Navigation
- blue: region 
- pink: main

## Expected behavior

No color contrast issues, text is easy to read.

## Screenshots

Screenshot landmarks over target page

## Extension (please complete the following information)

- OS: [e.g. Windows/Mac] Windows
- Version [e.g. 1.140.1] 2.4.1
- Browser Version [e.g Chrome 71.0] 74.0.3729.157
- Target Page [e.g www.bing.com] https://www.washington.edu/accesscomputing/AU/after.html#

## Are you willing to submit a PR?

If asked, will you be willing to submit a PR to fix this bug? No

## Did you search for similar existing issues?

Did you search for similar issues in our github issues or on [stackoverflow](https://stackoverflow.com/questions/tagged/accessibility-insights)
Yes

### PR DESCRIPTION
**Pull request by Shobhit1**
#### Description of changes

Update visualizations for landmark rule. 

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #694 
- [x] Added relevant unit test for your changes. (`yarn test`)
- [x] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x] Ran precheckin (`yarn precheckin`)
- [x] (UI changes only) Added screenshots/GIFs to description above
- [x] (UI changes only) Verified usability with NVDA/JAWS

##### Old
image

##### New

image

### CODE REVIEW

**Comment by Shobhit1** [comment]
Tagging @ferBonnin for a review.

**Comment by ferBonnin** [comment]
@cheade to take a look :)

**Comment by cheade** [comment]
This looks a lot easier for users to see now!

Only ask is to add that dashed line around the text box itself to give continuity to the design of landmarks :).

**Comment by ferBonnin** [comment]
At triage we said dashed line was nice to have, not needed to fix accessibility issue of contrast.

**Comment by ferBonnin** [comment]
At triage we said dashed line was nice to have, not needed to fix accessibility issue of contrast.

**Comment by cheade** [comment]
Dashed line addition is a very small line of CSS. I figured since we're updating the style already it would be beneficial to add polish at this time rather than do just minimum asks. 

Shobit was able to add it in very quickly, did a great job!

**Comment by smoralesd** [comment]
@Shobhit1 did you check if this affect the guidance content?

**Comment by Shobhit1** [comment]
> @Shobhit1 did you check if this affect the guidance content?

It doesn't.

**Comment by cheade** [comment]
The original dashed line around the region shouldn't have been changed at all. I just suggested adding the dashed line around the text box itself to match what was already there

**Pull request merged**
