### PR TITLE
fix: update scanDate to get current date

### PR DESCRIPTION
**Pull request by shanisebarona**
#### Details

Update scanDate to return current date for the date stamp populated as part of the exported results file title.

##### Motivation

Addresses the bug in issue  #3995.

#### Pull request checklist

- [x] Addresses an existing issue:  #3995
- [x] Ran `yarn fastpass`
- [x] Added/updated relevant unit test(s) (and ran `yarn test`)
- [x] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x] PR title *AND* final merge commit title both start with a semantic tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). See `CONTRIBUTING.md`.
- [/] (UI changes only) Added screenshots/GIFs to description above
- [/] (UI changes only) Verified usability with NVDA/JAWS

### CODE REVIEW

**Review by dbjorge — APPROVED** [review]

**Review by dbjorge — CHANGES_REQUESTED** [review]
It's surprising to me that this doesn't require a unit test update; there should probably be a test pinning the behavior here

**Comment by shanisebarona** [comment]
> It's surprising to me that this doesn't require a unit test update; there should probably be a test pinning the behavior here

@dbjorge I thought so too! In `report-export-dialog-factory.test.tsx`, it's seems to already be mocking the date function as desired. 

`const theDate = new Date(Date.UTC(2019, 2, 12, 9, 0));`
 and `getCurrentDate: () => theDate` in the `deps`.

unless this itself should be updated?

**Comment by dbjorge** [comment]
@shanisebarona Ideally we want the unit test to be verifying that the date used by the component comes from the place we expect it to; here, the test isn't verifying which of `scanCompleted` or `getCurrentDate` is being used. The way the test is wiring up the mock `getCurrentDate` implementation would be fine in isolation; the only issue is that the same date stub (`theDate`) is being re-used in several locations. Ideally, we'd want to pass in different dates for `scanCompleted` vs `getCurrentDate`, so the test can verify which one the actual component is using.

**Comment by shanisebarona** [comment]
Thank you @dbjorge, that was helpful, I've updated the test :)

**Review by dbjorge — APPROVED** [review]

**Pull request merged**
