### PR TITLE
chore: Optimizing Performance and Resource Utilization with Concurrent Function Execution

### PR DESCRIPTION
**Pull request by sanjaiyan-dev**
#### Details

This PR introduces a minor performance improvement by running the functions concurrently using `Promise.all`, which also enhances the efficient utilization of hardware resources.

##### Motivation

This change addresses a performance enhancement to utilize concurrency and improve resource utilization.

##### Context

N/A

#### Pull request checklist

- [n/a] Addresses an existing issue: N/A
- [x] Ran `yarn fastpass`
- [n/a] Added/updated relevant unit test(s) (and ran `yarn test`)
- [n.a] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x] PR title *AND* final merge commit title both start with a semantic tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). See `CONTRIBUTING.md`.
- [n/a] (UI changes only) Added screenshots/GIFs to description above
- [n/a] (UI changes only) Verified usability with NVDA/JAWS

### CODE REVIEW

**Comment by codeofdusk** [comment]
* Please update your PR description to use the template.
* Do you have evidence that these changes significantly improve performance? Benchmarks are ideal, but even a link to documentation helps.

**Comment by sanjaiyan-dev** [comment]
> * Please update your PR description to use the template.
> * Do you have evidence that these changes significantly improve performance? Benchmarks are ideal, but even a link to documentation helps.

Hi @codeofdusk,

I apologize for not running a specific benchmark test, but I've updated the description. Here are some resource links for reference:

1) [MDN docs - Promise.all](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all#description)
2) [MDN docs - Promise Concurrency](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#promise_concurrency)
3) [Blogs - JavaScript Promise.all](https://fjolt.com/article/javascript-promise-all?ref=hackernoon.com#conclusion)

I hope these resources are helpful.

**Review by codeofdusk — APPROVED** [review]
Seems okay to me, but I'd like a second review from @madalynrose or @JGibson2019 please.

**Comment by DaveTryon** [comment]
@sanjaiyan-dev The linter isn't happy. Please run `yarn format:fix` on your local machine, and be sure that running `yarn fastpass` locally reports clean before pushing the update. Thanks~

**Comment by sanjaiyan-dev** [comment]
> @sanjaiyan-dev The linter isn't happy. Please run `yarn format:fix` on your local machine, and be sure that running `yarn fastpass` locally reports clean before pushing the update. Thanks~

@DaveTryon  Done🤝

**Comment by DaveTryon** [comment]
Thanks, @sanjaiyan-dev!

**Comment by sanjaiyan-dev** [comment]
> Thanks, @sanjaiyan-dev! 

My Pleasure ✨

**Pull request merged**
